AWSTemplateFormatVersion: "2010-09-09"
Description: "Demo stack with issues for AI review"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.large       # Expensive, older gen
      ImageId: ami-1234567890abcdef0
      KeyName: my-key              # Hardcoded key name
      SecurityGroups:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0       # ❌ Insecure (open SSH to world)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-demo-bucket   # Hardcoded name, may cause conflict
