template_file: cloudformation-templates/fixed-lambda-permission-template.yaml
stack_name: q-demo-fixed-lambda
capabilities:
  - CAPABILITY_NAMED_IAM
parameter_overrides:
  FunctionName: qDemoFixed
tags:
  Environment: demo
  Project: q-demo
  Purpose: permission-fix-demo