version: 0.1
project_name: q-demo-lambda-deployment

deployments:
  - name: fixed-lambda-permission
    template_file: cloudformation-templates/fixed-lambda-permission-template.yaml
    stack_name: q-demo-fixed-lambda
    region: ap-south-1
    capabilities:
      - CAPABILITY_NAMED_IAM
    parameters:
      FunctionName: qDemoFixed
    tags:
      Environment: demo
      Project: q-demo
      Purpose: permission-fix-demo
